baseurl = "/"
title = "Teofil Nakov"
author = "Teofil Nakov"
copyright = "Copyright (c) 2019 Teofil Nakov"
canonifyurls = true
paginate = 3
theme = "hugo-orbit-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
# date_format = "2 January 2006"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

bio_full = "I am a postdoctoral researcher at the Alverson lab at the University of Arkansas Fayetteville."
bio_twitter = "teofil_nakov"

# Title of posts section on main page.
posts_title = "Posts"

# Number of posts to show on main page.
posts_count = 3

# Title of publications section on main page.
pubs_title = "Papers"

# Number of publications to show on main page.
pubs_count = 3

[[params.education]]
  course = "PhD Plant Biology"
  institution = "The University of Texas at Austin, Tx, USA"
  year = 2014
  
[[params.education]]
  course = "BSci Biochemistry & Physiology"
  institution = "Sts Cyril & Methodius University, Skopje, Macedonia"
  year = 2005

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:teofiln@gmail.com"
  text = "teofiln@gmail.com"
    
[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/teofilnakov"
  text = "@teofilnakov"
  site = "Twitter"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "//https://github.com/teofiln"
  text = "Teofil"
  site = "GitHub"

[[params.social]]
  icon = "researchgate"
  icon_pack = "ai"
  link = "https://www.researchgate.net/profile/Teofil_Nakov"
  text = "ResearchGate"

[[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.com/citations?user=2lKX40AAAAAJ&hl=en"
  text = "Google Scholar"

# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "/publication/"
  weight = 2

[[menu.main]]
  name = "Meetings"
  url = "/meeting/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 5
